---
R1:
    hostname: 192.168.130.13
    groups:
        - cisco_group
    data:
        type: "router"
        role: "office"
        ospf:
            ospf_rid: 192.168.130.13
            ospf_process: "1"
            ospf_networks:
                ip: "192.168.130.0"
                wild_card: "255.255.255.0"
                area: "0"

R2:
    hostname: 192.168.130.10
    groups:
        - cisco_group
    data:
        role: "office"
        type: "router"
        ospf:
            ospf_rid: 192.168.130.10
            ospf_process: "1"
            ospf_networks:
                ip: "192.168.130.0"
                wild_card: "255.255.255.0"
                area: "0"
R3:
    hostname: 192.168.130.11
    groups:
        - cisco_group
    data:
        role: "MFG"
        type: "router"
        ospf:
            ospf_rid: 192.168.130.11
            ospf_process: "1"
            ospf_networks:
                ip: "192.168.130.0"
                wild_card: "255.255.255.0"
                area: "0"
R4:
    hostname: 192.168.130.12
    groups:
        - cisco_group
    data:
        role: "MFG"
        type: "router"
        ospf:
            ospf_rid: 192.168.130.12
            ospf_process: "1"
            ospf_networks:
                ip: "192.168.130.0"
                wild_card: "255.255.255.0"
                area: "0"