---
vIOS4:
    hostname: 192.168.130.13
    groups:
        - cisco_group
    data: 
        storeID: LAB001
        city: HCM
        firewall: T

vIOS2:
    hostname: 192.168.130.10
    groups:
        - cisco_group

    data: 
        storeID: LAB002
        city: HN
        firewall: T
vIOS3:
    hostname: 192.168.130.11
    groups:
        - cisco_group
    data: 
        storeID: LAB001
        city: HCM

vIOS5:
    hostname: 192.168.130.12
    groups:
        - cisco_group
    data: 
        storeID: LAB004
        city: DN