---

inventory:
    plugin: SimpleInventory
    options:
        host_file: "/home/quandm/DATA/Git/netdevops/04.Lab_network_automation/config_file/inventory/hosts.yaml"
        group_file: "/home/quandm/DATA/Git/netdevops/04.Lab_network_automation/config_file/inventory/groups.yaml"
        defaults_file: "/home/quandm/DATA/Git/netdevops/04.Lab_network_automation/config_file/inventory/defaults.yaml"

runner:
    plugin: threaded
    options:
        num_workers: 10